// Generated by CoffeeScript 1.9.3
var AppComponent, DefaultRoute, HeaderComponent, HomeComponent, MainFeedComponent, ProjectCreateComponent, React, Reqwest, Route, RouteHandler, Router, a, div, h1, p, ref, routes;

require('./assets/stylesheets/main.scss');

require('./assets/stylesheets/header.scss');

React = require("react");

Reqwest = require("reqwest");

Router = require('react-router');

RouteHandler = Router.RouteHandler;

HeaderComponent = require("./components/header/HeaderComponent");

ref = React.DOM, div = ref.div, h1 = ref.h1, p = ref.p, a = ref.a;

AppComponent = React.createClass({
  getInitialState: function() {
    return {
      user: null,
      page: 'feed',
      selectedProject: null
    };
  },
  componentWillMount: function() {},
  getDefaultProps: function() {
    return {
      origin: process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : ''
    };
  },
  readFromAPI: function(url, success) {
    return Reqwest({
      url: url,
      type: 'json',
      method: 'get',
      contentType: 'application/json',
      success: success,
      error: function(error) {
        return console.log(url, error['response']);
      }
    });
  },
  render: function() {
    return div({
      "id": "content"
    }, React.createElement(HeaderComponent, {
      homeClicked: this.homeClicked,
      createClicked: this.createClicked,
      user: this.state.user
    }), React.createElement(RouteHandler, {
      origin: this.props.origin,
      readFromAPI: this.readFromAPI
    }));
  }
});

DefaultRoute = Router.DefaultRoute;

Route = Router.Route;

HomeComponent = require('./components/HomeComponent');

ProjectCreateComponent = require('./components/project/ProjectCreateComponent');

MainFeedComponent = require('./components/feed/MainFeedComponent');

routes = React.createElement(Route, {
  name: "App",
  path: "/",
  handler: AppComponent
}, React.createElement(Route, {
  name: "home",
  path: "/",
  handler: HomeComponent
}), React.createElement(Route, {
  name: "create",
  path: "create",
  handler: ProjectCreateComponent
}));

Router.run(routes, Router.HistoryLocation, function(Handler) {
  console.log(Handler);
  return React.render(React.createElement(Handler), document.body);
});
