// Generated by CoffeeScript 1.9.3
var AppComponent, HomeComponent, React, Reqwest, a, div, h1, p, ref;

require('./assets/stylesheets/main.scss');

require('./assets/stylesheets/header.scss');

React = require("react");

Reqwest = require("reqwest");

HomeComponent = require("./components/HomeComponent");

ref = React.DOM, div = ref.div, h1 = ref.h1, p = ref.p, a = ref.a;

AppComponent = React.createClass({
  getDefaultProps: function() {
    return {
      origin: process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : ''
    };
  },
  readFromAPI: function(url, success) {
    return Reqwest({
      url: url,
      type: 'json',
      method: 'get',
      contentType: 'application/json',
      success: success,
      error: function(error) {
        return console.log(url, error['response']);
      }
    });
  },
  render: function() {
    return div({
      "id": "content"
    }, React.createElement(HomeComponent, {
      origin: this.props.origin,
      readFromAPI: this.readFromAPI
    }));
  }
});

React.render(React.createElement(AppComponent), document.body);
