// Generated by CoffeeScript 1.9.3
var HeaderComponent, Link, React, Router, div, img, ref;

React = require("react");

ref = React.DOM, div = ref.div, img = ref.img;

Router = require('react-router');

Link = Router.Link;

HeaderComponent = React.createClass({
  render: function() {
    return div({
      "className": "navbar navbar-fixed-top"
    }, div({
      "className": "container-fluid header"
    }, div({
      "className": "logo"
    }, "Spaces"), React.createElement(Link, {
      to: "create"
    }, "create"), div({
      "id": "add_profile",
      "className": "upper_right"
    }, this.props.user ? img({
      "className": "profile",
      "src": this.props.user.image + "?sz=100"
    }) : void 0), div({
      "onClick": this.props.createClicked,
      "className": "create-button"
    }, "Create"), div({
      "className": "header-links"
    })));
  }
});

module.exports = HeaderComponent;
