// Generated by CoffeeScript 1.9.3
var Link, ProjectComponent, React, Router, a, div, i, img, ref, span;

React = require("react");

Router = require('react-router');

Link = Router.Link;

ref = React.DOM, div = ref.div, span = ref.span, img = ref.img, a = ref.a, i = ref.i;

ProjectComponent = React.createClass({
  render: function() {
    var tag_list;
    tag_list = this.props.project.tag_list.map(function(tag) {
      return span({
        key: tag
      }, tag);
    });
    return div({
      className: "feed-post"
    }, div({
      className: "row"
    }, div({
      className: "profile-container username-link",
      "user-id": this.props.user.id
    }, img({
      className: "profilepic-small",
      src: this.props.user.image
    }), div({
      className: "profile-text-wrapper"
    }, div({
      className: "username"
    }, this.props.user.first_name + " " + this.props.user.last_name), div({
      className: "timestamp"
    }, this.props.project.time_ago + " ago"))), div({
      className: "feed-links"
    }, this.props.project.github ? a({
      href: this.props.project.github
    }, i({
      className: "fa fa-github fa-3x"
    })) : null, this.props.project.dropbox ? a({
      href: this.props.project.dropbox
    }, i({
      className: "fa fa-dropbox fa-3x"
    })) : null)), div({
      className: "row"
    }, div({
      className: "project-title"
    }, this.props.project.name), div({
      className: "row"
    }, div({
      className: "project-desc-label"
    }, "Problem:"), div({
      className: "project-desc"
    }, this.props.project.problem)), div({
      className: "row"
    }, div({
      className: "project-desc-label"
    }, "Solution:"), div({
      className: "project-desc"
    }, this.props.project.problem)), React.createElement(Link, {
      to: "/project/" + this.props.project.id,
      className: "project-details-link"
    }, "Details"), div({
      className: "project-footer"
    }, div({
      className: "feedback"
    }, "Feedback: ", a({
      href: "/comments"
    }, span({
      className: "feedback-number"
    }, this.props.project.numComments))), div({
      className: "tags"
    }, "Tags: ", span({
      className: "tags-text"
    }, tag_list)))), div({
      className: "feed-separator"
    }));
  }
});

module.exports = ProjectComponent;
