// Generated by CoffeeScript 1.9.3
var ProjectCreateComponent, React, div;

React = require("react");

div = React.DOM.div;

ProjectCreateComponent = React.createClass({
  getInitialState: function() {
    return {
      name: "",
      problem: "",
      solution: "",
      info: "",
      github: "",
      dropbox: "",
      link: "",
      inProgress: false
    };
  },
  handleChange: function(e) {
    switch (e.target.name) {
      case "name":
        return this.setState({
          name: e.target.value
        });
      case "problem":
        return this.setState({
          problem: e.target.value
        });
      case "solution":
        return this.setState({
          solution: e.target.value
        });
      case "info":
        return this.setState({
          info: e.target.value
        });
      case "github":
        return this.setState({
          github: e.target.value
        });
      case "dropbox":
        return this.setState({
          dropbox: e.target.value
        });
      case "link":
        return this.setState({
          link: e.target.value
        });
    }
  },
  publish: function(e) {
    return e.preventDefault();
  },
  render: function() {
    var mainInputs, sidebarInputs;
    sidebarInputs = [
      {
        name: "github",
        stateValue: this.state.github
      }, {
        name: "dropbox",
        stateValue: this.state.dropbox
      }, {
        name: "link",
        stateValue: this.state.link
      }
    ];
    mainInputs = [
      {
        name: "problem",
        title: "Problem",
        placeholder: "Tell us what problem you are solving",
        stateValue: this.state.problem
      }, {
        name: "solution",
        title: "Solution",
        placeholder: "How are you going to solve the problem?",
        stateValue: this.state.solution
      }, {
        name: "info",
        title: "More Info",
        placeholder: "More information...",
        stateValue: this.state.info
      }
    ];
    return div({}, "create");
  }
});

module.exports = ProjectCreateComponent;
