json.text        @post.long
json.first       @current_user.firstName
json.last        @current_user.lastName
json.post_id     @post.id
json.user_id     @current_user.id
json.project_id  @post.project_id
json.projectName @post.project.name
json.usr_img     @current_user.image
json.numComments @post.comments.count
